### ISSUE TITLE
Based on encrypted tensor?

### ISSUE THREAD

**Issue by mialuyao** [TomHeaven/crypten_cifar10_cuda_distributed#1]
Hello!

I want to implement image classification under MPC based on the crypten framework. 
Does this project seem to be based on the crypten framework to implement distributed training?
Not based on encrypted tensors?

**Comment by dorafan** [comment]
Hi, I have the same question. Do you get the answer?
It looks like the model is encrypted by crypten framework, only the inputs use encrypted tensors
